# Schema for the configuration files of the Byoh theme.

byoh.settings:
  type: theme_settings
  label: 'Byoh settings'
  mapping:
    # @todo Module-specific settings should be defined by the module:
    #   https://drupal.org/node/2235901.
    shortcut_module_link:
      type: boolean
      label: 'Shortcut module link'
